import React, { useState, useMemo } from 'react';
import { 
  Compass, 
  Calendar as CalendarIcon, 
  Moon, 
  Sun, 
  Flag, 
  Globe, 
  History, 
  Cake, 
  Lightbulb, 
  ShieldCheck, 
  Share2, 
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Sparkles
} from 'lucide-react';
import { UserSettings } from '../../types';
import { 
  formatDateToISO, 
  getDayOfYear, 
  getWeekNumber, 
  isLeapYear, 
  getQuarter, 
  DAY_NAMES_FULL, 
  MONTH_NAMES 
} from '../../utils/dateCalculations';
import { getHolidaysForDate } from '../../data/holidaysData';
import { getFestivalsForDate } from '../../data/festivalsData';
import { getHistoricalEventsForDate } from '../../data/historicalEventsData';
import { getBirthdaysForDate, getDeathsForDate } from '../../data/birthdaysDeathsData';
import { getDailyFactForDate } from '../../data/dailyFactsData';
import { getObservancesForDate } from '../../data/observancesData';
import { getMoonPhase, calculateSunTimes } from '../../utils/astronomyCalculations';
import { getHijriDate } from '../../utils/hijriCalculations';
import { calculatePanchang } from '../../utils/panchangCalculations';

interface DateExplorerViewProps {
  selectedDate: Date;
  onSelectDate: (date: Date) => void;
  settings: UserSettings;
  onOpenAddEvent: (dateStr: string) => void;
}

export const DateExplorerView: React.FC<DateExplorerViewProps> = ({
  selectedDate,
  onSelectDate,
  settings,
  onOpenAddEvent
}) => {
  const [dateInputVal, setDateInputVal] = useState(formatDateToISO(selectedDate));
  const [copied, setCopied] = useState(false);

  const dateStr = formatDateToISO(selectedDate);
  const year = selectedDate.getFullYear();
  const month = selectedDate.getMonth() + 1;
  const day = selectedDate.getDate();

  const handleDateChange = (val: string) => {
    setDateInputVal(val);
    if (val) {
      const [y, m, d] = val.split('-').map(Number);
      if (y && m && d) {
        onSelectDate(new Date(y, m - 1, d));
      }
    }
  };

  const handleShiftDay = (delta: number) => {
    const next = new Date(selectedDate);
    next.setDate(next.getDate() + delta);
    onSelectDate(next);
    setDateInputVal(formatDateToISO(next));
  };

  // Calculations
  const dayOfYear = getDayOfYear(selectedDate);
  const weekNum = getWeekNumber(selectedDate);
  const quarter = getQuarter(selectedDate);
  const leapYear = isLeapYear(year);
  const totalDays = leapYear ? 366 : 365;

  const holidays = useMemo(() => getHolidaysForDate(dateStr, settings.stateProvince), [dateStr, settings.stateProvince]);
  const festivals = useMemo(() => getFestivalsForDate(dateStr), [dateStr]);
  const observances = useMemo(() => getObservancesForDate(month, day), [month, day]);
  const historyEvents = useMemo(() => getHistoricalEventsForDate(month, day), [month, day]);
  const birthdays = useMemo(() => getBirthdaysForDate(month, day), [month, day]);
  const deaths = useMemo(() => getDeathsForDate(month, day), [month, day]);
  const dailyFact = useMemo(() => getDailyFactForDate(month, day), [month, day]);
  const moonPhase = useMemo(() => getMoonPhase(selectedDate), [selectedDate]);
  const sunTimes = useMemo(() => calculateSunTimes(selectedDate, 28.6139, 77.2090), [selectedDate]);
  const hijri = useMemo(() => getHijriDate(selectedDate), [selectedDate]);
  const panchang = useMemo(() => calculatePanchang(selectedDate), [selectedDate]);

  const handleCopySummary = () => {
    const summary = `📅 Date Analysis for ${dateStr} (${DAY_NAMES_FULL[selectedDate.getDay()]}):
- Gregorian: Day ${dayOfYear}/${totalDays}, Week ${weekNum}, Q${quarter}
- Islamic Hijri: ${hijri.formatted}
- Vedic Panchang: ${panchang.tithi.name}, ${panchang.nakshatra.name}
- Moon Phase: ${moonPhase.name} (${moonPhase.phasePercentage}% illuminated)
- Holidays: ${holidays.map(h => h.name).join(', ') || 'None'}
- Festivals: ${festivals.map(f => f.name).join(', ') || 'None'}
- Historical Spotlight: ${historyEvents[0]?.title || 'None recorded'}
— Generated by Ali Calendar`;
    
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div id="date-explorer-container" className="space-y-6 animate-fade-in">
      {/* Top Picker & Navigator */}
      <div className="bg-white dark:bg-slate-900 rounded-3xl p-6 border border-slate-200/80 dark:border-slate-800 shadow-sm flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-3 w-full md:w-auto">
          <div className="w-10 h-10 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400 flex items-center justify-center shrink-0">
            <Compass className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-slate-900 dark:text-white">
              Universal Date Explorer
            </h2>
            <p className="text-xs text-slate-500">
              Deep chronological, astronomical, and cultural inspection for any date.
            </p>
          </div>
        </div>

        {/* Date Selector & Shift buttons */}
        <div className="flex items-center gap-2 w-full md:w-auto justify-end">
          <button
            onClick={() => handleShiftDay(-1)}
            className="p-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-700 dark:text-slate-200 hover:bg-white dark:hover:bg-slate-700 transition-colors"
            title="Previous Day"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>

          <input
            id="explorer-date-picker"
            type="date"
            value={dateInputVal}
            onChange={(e) => handleDateChange(e.target.value)}
            className="px-3.5 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-xs font-bold text-slate-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:outline-none"
          />

          <button
            onClick={() => handleShiftDay(1)}
            className="p-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-700 dark:text-slate-200 hover:bg-white dark:hover:bg-slate-700 transition-colors"
            title="Next Day"
          >
            <ArrowRight className="w-4 h-4" />
          </button>

          <button
            onClick={handleCopySummary}
            className="px-3 py-2 rounded-xl bg-indigo-50 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800 text-xs font-semibold flex items-center gap-1.5 hover:bg-indigo-100 transition-colors"
            title="Copy date dossier"
          >
            <Share2 className="w-3.5 h-3.5" />
            <span>{copied ? 'Copied!' : 'Share Dossier'}</span>
          </button>
        </div>
      </div>

      {/* Date Header Highlight Card */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white rounded-3xl p-6 sm:p-8 shadow-xl border border-slate-800 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/10 pb-4">
          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-indigo-300">
              {DAY_NAMES_FULL[selectedDate.getDay()]}
            </span>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-white">
              {selectedDate.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
            </h1>
          </div>
          <div className="flex items-center gap-2">
            <span className="px-3 py-1 rounded-full bg-white/10 text-xs font-medium text-indigo-200">
              Quarter {quarter}
            </span>
            <span className="px-3 py-1 rounded-full bg-white/10 text-xs font-medium text-indigo-200">
              Week {weekNum}
            </span>
            <span className="px-3 py-1 rounded-full bg-white/10 text-xs font-medium text-indigo-200">
              Day {dayOfYear} / {totalDays}
            </span>
          </div>
        </div>

        {/* Multi-System Parallel Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2">
          {/* Islamic Hijri */}
          <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-1">
            <div className="flex items-center gap-2 text-emerald-400 text-xs font-bold">
              <Moon className="w-4 h-4" />
              <span>Islamic Hijri Calendar</span>
            </div>
            <p className="text-sm font-bold text-white">{hijri.formatted}</p>
            <p className="text-[11px] text-slate-300">
              Month: {hijri.monthName} ({hijri.monthNumber}/12) • {hijri.isSacredMonth ? '🌟 Sacred Month' : 'Standard Month'}
            </p>
            <p className="text-[10px] text-emerald-300/80 italic">Umm al-Qura Algorithmic Projection</p>
          </div>

          {/* Vedic Panchang */}
          <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-1">
            <div className="flex items-center gap-2 text-amber-400 text-xs font-bold">
              <Sun className="w-4 h-4" />
              <span>Vedic Panchang</span>
            </div>
            <p className="text-sm font-bold text-white">{panchang.tithi.name}</p>
            <p className="text-[11px] text-slate-300">
              Nakshatra: {panchang.nakshatra.name} • Paksha: {panchang.paksha}
            </p>
            <p className="text-[10px] text-amber-300/80 italic">Drik Siddhanta Ephemeris Calculation</p>
          </div>

          {/* Astronomy */}
          <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-1">
            <div className="flex items-center gap-2 text-purple-400 text-xs font-bold">
              <Globe className="w-4 h-4" />
              <span>Astronomy & Solar Times</span>
            </div>
            <p className="text-sm font-bold text-white">{moonPhase.name}</p>
            <p className="text-[11px] text-slate-300">
              Sunrise: {sunTimes.sunrise} • Sunset: {sunTimes.sunset} • {sunTimes.dayLength}
            </p>
            <p className="text-[10px] text-purple-300/80 italic">Illumination: {moonPhase.phasePercentage}%</p>
          </div>
        </div>
      </div>

      {/* Grid: Holidays, Festivals & Observances */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Holidays & Festivals Card */}
        <div className="bg-white dark:bg-slate-900 rounded-3xl p-6 border border-slate-200/80 dark:border-slate-800 shadow-sm space-y-4">
          <div className="flex items-center gap-2 text-xs font-bold text-orange-800 dark:text-orange-400">
            <Flag className="w-4 h-4" />
            <span>Holidays & Observances on {dateStr}</span>
          </div>

          {holidays.length === 0 && festivals.length === 0 && observances.length === 0 ? (
            <p className="text-xs text-slate-500 py-4 text-center">
              No statutory gazetted holidays or major religious festivals registered on this date.
            </p>
          ) : (
            <div className="space-y-3">
              {holidays.map(h => (
                <div key={h.id} className="p-3 rounded-2xl bg-orange-50/60 dark:bg-orange-950/30 border border-orange-200 dark:border-orange-900/50">
                  <div className="flex items-center justify-between">
                    <h4 className="text-xs font-bold text-slate-900 dark:text-white">🇮🇳 {h.name}</h4>
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-orange-100 dark:bg-orange-900 text-orange-800 dark:text-orange-200 uppercase">
                      {h.holidayType}
                    </span>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-slate-300 mt-1">{h.description}</p>
                  <p className="text-[10px] text-slate-400 mt-1">Source: {h.sourceName}</p>
                </div>
              ))}

              {festivals.map(f => (
                <div key={f.id} className="p-3 rounded-2xl bg-emerald-50/60 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-900/50">
                  <div className="flex items-center justify-between">
                    <h4 className="text-xs font-bold text-slate-900 dark:text-white">✨ {f.name}</h4>
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-emerald-100 dark:bg-emerald-900 text-emerald-800 dark:text-emerald-200 uppercase">
                      {f.religion}
                    </span>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-slate-300 mt-1">{f.description}</p>
                  {f.rituals && <p className="text-[11px] text-emerald-700 dark:text-emerald-300 mt-1">Rituals: {f.rituals}</p>}
                </div>
              ))}

              {observances.map(obs => (
                <div key={obs.id} className="p-3 rounded-2xl bg-blue-50/60 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-900/50">
                  <div className="flex items-center justify-between">
                    <h4 className="text-xs font-bold text-slate-900 dark:text-white">🌐 {obs.officialName}</h4>
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200">
                      {obs.organization}
                    </span>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-slate-300 mt-1">{obs.purpose}</p>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Historical Events Card */}
        <div className="bg-white dark:bg-slate-900 rounded-3xl p-6 border border-slate-200/80 dark:border-slate-800 shadow-sm space-y-4">
          <div className="flex items-center gap-2 text-xs font-bold text-purple-800 dark:text-purple-400">
            <History className="w-4 h-4" />
            <span>On This Day in History ({month}/{day})</span>
          </div>

          {historyEvents.length === 0 ? (
            <p className="text-xs text-slate-500 py-4 text-center">
              No historical milestones indexed for this exact day in the local archive.
            </p>
          ) : (
            <div className="space-y-3">
              {historyEvents.map(evt => (
                <div key={evt.id} className="p-3 rounded-2xl bg-purple-50/50 dark:bg-purple-950/30 border border-purple-200/60 dark:border-purple-900/40 space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-extrabold text-purple-700 dark:text-purple-400 font-mono">
                      Year {evt.year}
                    </span>
                    <span className="text-[10px] font-bold uppercase text-slate-400">
                      {evt.category}
                    </span>
                  </div>
                  <h4 className="text-xs font-bold text-slate-900 dark:text-white">{evt.title}</h4>
                  <p className="text-[11px] text-slate-600 dark:text-slate-300 leading-relaxed">{evt.description}</p>
                  <p className="text-[10px] text-slate-400">Source: {evt.sourceName}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Famous Birthdays & Deaths */}
      <div className="bg-white dark:bg-slate-900 rounded-3xl p-6 border border-slate-200/80 dark:border-slate-800 shadow-sm space-y-4">
        <div className="flex items-center gap-2 text-xs font-bold text-pink-800 dark:text-pink-400">
          <Cake className="w-4 h-4" />
          <span>Born or Remembered on {selectedDate.toLocaleDateString('en-US', { month: 'long', day: 'numeric' })}</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {birthdays.map(p => (
            <div key={p.id} className="p-4 rounded-2xl bg-pink-50/50 dark:bg-pink-950/20 border border-pink-200/60 dark:border-pink-900/40 space-y-1.5">
              <div className="flex items-center justify-between">
                <h4 className="text-xs font-bold text-slate-900 dark:text-white">{p.name}</h4>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-pink-100 dark:bg-pink-900 text-pink-700 dark:text-pink-300">
                  Born {p.birthDate.split('-')[0]}
                </span>
              </div>
              <p className="text-xs font-semibold text-pink-700 dark:text-pink-400">{p.profession} ({p.country})</p>
              <p className="text-[11px] text-slate-600 dark:text-slate-300">{p.shortBio}</p>
              <p className="text-[10px] text-slate-500 font-medium">Major work: {p.majorContribution}</p>
            </div>
          ))}

          {deaths.map(p => (
            <div key={p.id} className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/40 border border-slate-200 dark:border-slate-700 space-y-1.5">
              <div className="flex items-center justify-between">
                <h4 className="text-xs font-bold text-slate-900 dark:text-white">{p.name}</h4>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-slate-200 dark:bg-slate-700 text-slate-700 dark:text-slate-300">
                  Passed away {p.deathDate}
                </span>
              </div>
              <p className="text-xs font-semibold text-slate-600 dark:text-slate-400">{p.profession} ({p.country})</p>
              <p className="text-[11px] text-slate-600 dark:text-slate-300">{p.shortBio}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
